//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : db_a99dc4_maimf
	/// Data Source    : SQL6031.site4now.net
	/// Server Version : 16.00.4035
	/// </summary>
	public partial class DbA99dc4MaimfDB : LinqToDB.Data.DataConnection
	{
		public ITable<Approval>            Approvals            { get { return this.GetTable<Approval>(); } }
		public ITable<ApprovalRequest>     ApprovalRequests     { get { return this.GetTable<ApprovalRequest>(); } }
		public ITable<Basket>              Baskets              { get { return this.GetTable<Basket>(); } }
		public ITable<BasketLine>          BasketLines          { get { return this.GetTable<BasketLine>(); } }
		public ITable<BusTicket>           BusTickets           { get { return this.GetTable<BusTicket>(); } }
		public ITable<City>                Cities               { get { return this.GetTable<City>(); } }
		public ITable<CompanyProduct>      CompanyProducts      { get { return this.GetTable<CompanyProduct>(); } }
		public ITable<County>              Counties             { get { return this.GetTable<County>(); } }
		public ITable<HotelProduct>        HotelProducts        { get { return this.GetTable<HotelProduct>(); } }
		public ITable<Link>                Links                { get { return this.GetTable<Link>(); } }
		public ITable<PersonDataInRequest> PersonDataInRequests { get { return this.GetTable<PersonDataInRequest>(); } }
		public ITable<ProductCategory>     ProductCategories    { get { return this.GetTable<ProductCategory>(); } }
		public ITable<ProductComment>      ProductComments      { get { return this.GetTable<ProductComment>(); } }
		public ITable<Region>              Regions              { get { return this.GetTable<Region>(); } }
		public ITable<Request>             Requests             { get { return this.GetTable<Request>(); } }
		public ITable<Role>                Roles                { get { return this.GetTable<Role>(); } }
		public ITable<Status>              Status               { get { return this.GetTable<Status>(); } }
		public ITable<Ststu>               Ststus               { get { return this.GetTable<Ststu>(); } }
		public ITable<TypeProduct>         TypeProducts         { get { return this.GetTable<TypeProduct>(); } }
		public ITable<User>                Users                { get { return this.GetTable<User>(); } }
		public ITable<UserFavProduct>      UserFavProducts      { get { return this.GetTable<UserFavProduct>(); } }
		public ITable<UserPrData>          UserPrData           { get { return this.GetTable<UserPrData>(); } }

		public DbA99dc4MaimfDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbA99dc4MaimfDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbA99dc4MaimfDB(LinqToDBConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbA99dc4MaimfDB(LinqToDBConnectionOptions<DbA99dc4MaimfDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="Approval")]
	public partial class Approval
	{
		[Column(),                      PrimaryKey, Identity] public int Id                { get; set; } // int
		[Column(),                      NotNull             ] public int IsOk              { get; set; } // int
		[Column("Approval_request_id"), NotNull             ] public int ApprovalRequestId { get; set; } // int

		#region Associations

		/// <summary>
		/// FK__Approval__Approv__5DCAEF64 (dbo.Approval_request)
		/// </summary>
		[Association(ThisKey="ApprovalRequestId", OtherKey="Id", CanBeNull=false)]
		public ApprovalRequest ApprovalRequest { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Approval_request")]
	public partial class ApprovalRequest
	{
		[PrimaryKey, Identity] public int      Id     { get; set; } // int
		[Column,     NotNull ] public int      UserId { get; set; } // int
		[Column,     NotNull ] public DateTime Date   { get; set; } // date

		#region Associations

		/// <summary>
		/// FK__Approval__Approv__5DCAEF64_BackReference (dbo.Approval)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ApprovalRequestId", CanBeNull=true)]
		public IEnumerable<Approval> ApprovalApprov5Dcaefs { get; set; }

		/// <summary>
		/// FK__Approval___UserI__5AEE82B9 (dbo.User)
		/// </summary>
		[Association(ThisKey="UserId", OtherKey="Id", CanBeNull=false)]
		public User User { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Basket")]
	public partial class Basket
	{
		[PrimaryKey, Identity   ] public int      Id      { get; set; } // int
		[Column,        Nullable] public int?     UserId  { get; set; } // int
		[Column,     NotNull    ] public DateTime DateIns { get; set; } // date

		#region Associations

		/// <summary>
		/// FK__Basket_Li__Baske__3E1D39E1_BackReference (dbo.Basket_Line)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="BasketId", CanBeNull=true)]
		public IEnumerable<BasketLine> LiBaske3E1D39E { get; set; }

		/// <summary>
		/// FK__Basket__UserId__3C34F16F (dbo.User)
		/// </summary>
		[Association(ThisKey="UserId", OtherKey="Id", CanBeNull=true)]
		public User User { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Basket_Line")]
	public partial class BasketLine
	{
		[Column,    Nullable] public int? BasketId    { get; set; } // int
		[Column, NotNull    ] public int  ProductId   { get; set; } // int
		[Column,    Nullable] public int? ProductType { get; set; } // int
		[Column,    Nullable] public int? Count       { get; set; } // int

		#region Associations

		/// <summary>
		/// FK__Basket_Li__Baske__3E1D39E1 (dbo.Basket)
		/// </summary>
		[Association(ThisKey="BasketId", OtherKey="Id", CanBeNull=true)]
		public Basket Basket { get; set; }

		/// <summary>
		/// FK__Basket_Li__Produ__3F115E1A (dbo.ProductCategory)
		/// </summary>
		[Association(ThisKey="ProductType", OtherKey="Id", CanBeNull=true)]
		public ProductCategory BasketLiProdu3F115E1A { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Bus_Tickets")]
	public partial class BusTicket
	{
		[PrimaryKey, Identity   ] public int      Id          { get; set; } // int
		[Column,     NotNull    ] public string   Name        { get; set; } // nvarchar(100)
		[Column,     NotNull    ] public int      StartCity   { get; set; } // int
		[Column,     NotNull    ] public int      EndCity     { get; set; } // int
		[Column,     NotNull    ] public decimal  Price       { get; set; } // decimal(18, 0)
		[Column,     NotNull    ] public int      TravelTime  { get; set; } // int
		[Column,     NotNull    ] public int      NumberSeats { get; set; } // int
		[Column,     NotNull    ] public string   BusImage    { get; set; } // nvarchar(2000)
		[Column,     NotNull    ] public DateTime DateStart   { get; set; } // datetime2(7)
		[Column,        Nullable] public string   StartAdress { get; set; } // nvarchar(100)
		[Column,        Nullable] public string   EndAdress   { get; set; } // nvarchar(100)

		#region Associations

		/// <summary>
		/// FK__Bus_Ticke__EndCi__2DE6D218 (dbo.City)
		/// </summary>
		[Association(ThisKey="EndCity", OtherKey="Id", CanBeNull=false)]
		public City BusTickeEndCi2DE6D { get; set; }

		/// <summary>
		/// FK__Bus_Ticke__Start__2CF2ADDF (dbo.City)
		/// </summary>
		[Association(ThisKey="StartCity", OtherKey="Id", CanBeNull=false)]
		public City BusTickeStart2CF2ADDF { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="City")]
	public partial class City
	{
		[PrimaryKey, Identity   ] public int    Id       { get; set; } // int
		[Column,     NotNull    ] public string Name     { get; set; } // nvarchar(50)
		[Column,        Nullable] public int?   RegionId { get; set; } // int
		[Column,        Nullable] public string Link     { get; set; } // nvarchar(2000)

		#region Associations

		/// <summary>
		/// FK__Bus_Ticke__EndCi__2DE6D218_BackReference (dbo.Bus_Tickets)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="EndCity", CanBeNull=true)]
		public IEnumerable<BusTicket> BusTickeEndCi2DE6D { get; set; }

		/// <summary>
		/// FK__Bus_Ticke__Start__2CF2ADDF_BackReference (dbo.Bus_Tickets)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="StartCity", CanBeNull=true)]
		public IEnumerable<BusTicket> BusTickeStart2CF2Addfs { get; set; }

		/// <summary>
		/// FK__Hotel_Pro__CityI__1AD3FDA4_BackReference (dbo.Hotel_Product)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="CityId", CanBeNull=true)]
		public IEnumerable<HotelProduct> HotelProCityI1AD3Fdas { get; set; }

		/// <summary>
		/// FK__City__RegionId__02084FDA (dbo.Region)
		/// </summary>
		[Association(ThisKey="RegionId", OtherKey="Id", CanBeNull=true)]
		public Region Region { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Company_Product")]
	public partial class CompanyProduct
	{
		[PrimaryKey, Identity   ] public int     Id              { get; set; } // int
		[Column,        Nullable] public string  Name            { get; set; } // nvarchar(100)
		[Column,        Nullable] public string  Description     { get; set; } // nvarchar(1000)
		[Column,        Nullable] public string  ShorDescription { get; set; } // nvarchar(500)
		[Column,     NotNull    ] public decimal Price           { get; set; } // decimal(18, 2)
		[Column,     NotNull    ] public int     CategoriId      { get; set; } // int
		[Column,        Nullable] public string  Image           { get; set; } // nvarchar(2000)

		#region Associations

		/// <summary>
		/// FK__Product__Categor__412EB0B6 (dbo.ProductCategory)
		/// </summary>
		[Association(ThisKey="CategoriId", OtherKey="Id", CanBeNull=false)]
		public ProductCategory Categori { get; set; }

		/// <summary>
		/// FK__ProductCo__Produ__44FF419A_BackReference (dbo.ProductComment)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ProductId", CanBeNull=true)]
		public IEnumerable<ProductComment> ProductCoProdu44FF419A { get; set; }

		/// <summary>
		/// FK__Request__Product__534D60F1_BackReference (dbo.Request)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ProductId", CanBeNull=true)]
		public IEnumerable<Request> RequestProduct534D60F { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="County")]
	public partial class County
	{
		[PrimaryKey, Identity] public int    Id   { get; set; } // int
		[Column,     NotNull ] public string Name { get; set; } // nvarchar(60)

		#region Associations

		/// <summary>
		/// FK__Region__CountyId__7F2BE32F_BackReference (dbo.Region)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="CountyId", CanBeNull=true)]
		public IEnumerable<Region> RegionCountyId7F2BE32F { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Hotel_Product")]
	public partial class HotelProduct
	{
		[Column(),                     NotNull    ] public int    Id               { get; set; } // int
		[Column(),                     NotNull    ] public string Name             { get; set; } // nvarchar(200)
		[Column(),                     NotNull    ] public double Price            { get; set; } // float
		[Column(),                     NotNull    ] public int    CityId           { get; set; } // int
		[Column("Distance_To_Center"), NotNull    ] public double DistanceToCenter { get; set; } // float
		[Column(),                        Nullable] public string MainImage        { get; set; } // nvarchar(max)

		#region Associations

		/// <summary>
		/// FK__Hotel_Pro__CityI__1AD3FDA4 (dbo.City)
		/// </summary>
		[Association(ThisKey="CityId", OtherKey="Id", CanBeNull=false)]
		public City City { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Link")]
	public partial class Link
	{
		[Column(),       PrimaryKey, Identity] public int    Id         { get; set; } // int
		[Column(),       NotNull             ] public string Name       { get; set; } // nvarchar(60)
		[Column(),       NotNull             ] public int    Number     { get; set; } // int
		[Column("Link"), NotNull             ] public string LinkColumn { get; set; } // nvarchar(max)
	}

	[Table(Schema="dbo", Name="PersonDataInRequest")]
	public partial class PersonDataInRequest
	{
		[PrimaryKey, Identity   ] public int    Id           { get; set; } // int
		[Column,        Nullable] public int?   RequestId    { get; set; } // int
		[Column,     NotNull    ] public bool   Who          { get; set; } // bit
		[Column,     NotNull    ] public bool   Document     { get; set; } // bit
		[Column,     NotNull    ] public string Name         { get; set; } // nvarchar(60)
		[Column,     NotNull    ] public string LastName     { get; set; } // nvarchar(60)
		[Column,     NotNull    ] public int    TelNumber    { get; set; } // int
		[Column,     NotNull    ] public string Mail         { get; set; } // nvarchar(60)
		[Column,     NotNull    ] public int    SerialNumber { get; set; } // int
		[Column,        Nullable] public string HotelAdress  { get; set; } // nvarchar(150)
		[Column,        Nullable] public string HotelName    { get; set; } // nvarchar(150)

		#region Associations

		/// <summary>
		/// FK__PersonDat__Reque__5629CD9C (dbo.Request)
		/// </summary>
		[Association(ThisKey="RequestId", OtherKey="Id", CanBeNull=true)]
		public Request Request { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="ProductCategory")]
	public partial class ProductCategory
	{
		[PrimaryKey, Identity] public int    Id   { get; set; } // int
		[Column,     NotNull ] public string Name { get; set; } // nvarchar(45)

		#region Associations

		/// <summary>
		/// FK__Basket_Li__Produ__3F115E1A_BackReference (dbo.Basket_Line)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ProductType", CanBeNull=true)]
		public IEnumerable<BasketLine> BasketLiProdu3F115E1A { get; set; }

		/// <summary>
		/// FK__Product__Categor__412EB0B6_BackReference (dbo.Company_Product)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="CategoriId", CanBeNull=true)]
		public IEnumerable<CompanyProduct> ProductCategor412EB0B { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="ProductComment")]
	public partial class ProductComment
	{
		[PrimaryKey, Identity] public int    Id        { get; set; } // int
		[Column,     NotNull ] public int    UserId    { get; set; } // int
		[Column,     NotNull ] public int    ProductId { get; set; } // int
		[Column,     NotNull ] public string Comment   { get; set; } // nvarchar(400)

		#region Associations

		/// <summary>
		/// FK__ProductCo__Produ__44FF419A (dbo.Company_Product)
		/// </summary>
		[Association(ThisKey="ProductId", OtherKey="Id", CanBeNull=false)]
		public CompanyProduct Product { get; set; }

		/// <summary>
		/// FK__ProductCo__UserI__440B1D61 (dbo.User)
		/// </summary>
		[Association(ThisKey="UserId", OtherKey="Id", CanBeNull=false)]
		public User User { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Region")]
	public partial class Region
	{
		[PrimaryKey, Identity] public int    Id       { get; set; } // int
		[Column,     NotNull ] public string Name     { get; set; } // nvarchar(60)
		[Column,     NotNull ] public int    CountyId { get; set; } // int

		#region Associations

		/// <summary>
		/// FK__City__RegionId__02084FDA_BackReference (dbo.City)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="RegionId", CanBeNull=true)]
		public IEnumerable<City> CityRegionId02084Fdas { get; set; }

		/// <summary>
		/// FK__Region__CountyId__7F2BE32F (dbo.County)
		/// </summary>
		[Association(ThisKey="CountyId", OtherKey="Id", CanBeNull=false)]
		public County County { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Request")]
	public partial class Request
	{
		[PrimaryKey, Identity   ] public int      Id        { get; set; } // int
		[Column,     NotNull    ] public int      UserId    { get; set; } // int
		[Column,     NotNull    ] public int      ProductId { get; set; } // int
		[Column,     NotNull    ] public DateTime Date      { get; set; } // date
		[Column,     NotNull    ] public int      People    { get; set; } // int
		[Column,        Nullable] public int?     Child     { get; set; } // int
		[Column,        Nullable] public int?     Adult     { get; set; } // int

		#region Associations

		/// <summary>
		/// FK__PersonDat__Reque__5629CD9C_BackReference (dbo.PersonDataInRequest)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="RequestId", CanBeNull=true)]
		public IEnumerable<PersonDataInRequest> PersonDatReque5629CD9C { get; set; }

		/// <summary>
		/// FK__Request__Product__534D60F1 (dbo.Company_Product)
		/// </summary>
		[Association(ThisKey="ProductId", OtherKey="Id", CanBeNull=false)]
		public CompanyProduct Product { get; set; }

		/// <summary>
		/// FK__Request__UserId__52593CB8 (dbo.User)
		/// </summary>
		[Association(ThisKey="UserId", OtherKey="Id", CanBeNull=false)]
		public User User { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Role")]
	public partial class Role
	{
		[PrimaryKey, Identity] public int    Id   { get; set; } // int
		[Column,     NotNull ] public string Name { get; set; } // nvarchar(45)

		#region Associations

		/// <summary>
		/// FK__User__RoleId__398D8EEE_BackReference (dbo.User)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="RoleId", CanBeNull=true)]
		public IEnumerable<User> UserRoleId398D8Eees { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Status")]
	public partial class Status
	{
		[PrimaryKey, Identity] public int    Id   { get; set; } // int
		[Column,     NotNull ] public string Name { get; set; } // nvarchar(40)
	}

	[Table(Schema="dbo", Name="Ststus")]
	public partial class Ststu
	{
		[PrimaryKey, Identity] public int    Id   { get; set; } // int
		[Column,     NotNull ] public string Name { get; set; } // nvarchar(40)

		#region Associations

		/// <summary>
		/// FK__User__Status__7C4F7684_BackReference (dbo.User)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="Status", CanBeNull=true)]
		public IEnumerable<User> UserStatus7C4F { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="TypeProduct")]
	public partial class TypeProduct
	{
		[PrimaryKey, Identity] public int    Id   { get; set; } // int
		[Column,     NotNull ] public string Name { get; set; } // nvarchar(100)

		#region Associations

		/// <summary>
		/// FK__UserFavPr__Produ__2180FB33_BackReference (dbo.UserFavProduct)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ProductType", CanBeNull=true)]
		public IEnumerable<UserFavProduct> UserFavPrProdu2180Fbs { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="User")]
	public partial class User
	{
		[PrimaryKey, Identity   ] public int      Id       { get; set; } // int
		[Column,     NotNull    ] public string   Mail     { get; set; } // nvarchar(60)
		[Column,     NotNull    ] public DateTime DateReg  { get; set; } // date
		[Column,        Nullable] public int?     RoleId   { get; set; } // int
		[Column,     NotNull    ] public string   Login    { get; set; } // nvarchar(50)
		[Column,     NotNull    ] public string   Password { get; set; } // nvarchar(50)
		[Column,     NotNull    ] public int      Status   { get; set; } // int

		#region Associations

		/// <summary>
		/// FK__Approval___UserI__5AEE82B9_BackReference (dbo.Approval_request)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="UserId", CanBeNull=true)]
		public IEnumerable<ApprovalRequest> ApprovalUserI5AEE82B { get; set; }

		/// <summary>
		/// FK__Basket__UserId__3C34F16F_BackReference (dbo.Basket)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="UserId", CanBeNull=true)]
		public IEnumerable<Basket> BasketUserId3C34F16F { get; set; }

		/// <summary>
		/// FK__ProductCo__UserI__440B1D61_BackReference (dbo.ProductComment)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="UserId", CanBeNull=true)]
		public IEnumerable<ProductComment> ProductCoUserI440B1D { get; set; }

		/// <summary>
		/// FK__Request__UserId__52593CB8_BackReference (dbo.Request)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="UserId", CanBeNull=true)]
		public IEnumerable<Request> RequestUserId52593Cbs { get; set; }

		/// <summary>
		/// FK__User__RoleId__398D8EEE (dbo.Role)
		/// </summary>
		[Association(ThisKey="RoleId", OtherKey="Id", CanBeNull=true)]
		public Role Role { get; set; }

		/// <summary>
		/// FK__User__Status__7C4F7684 (dbo.Ststus)
		/// </summary>
		[Association(ThisKey="Status", OtherKey="Id", CanBeNull=false)]
		public Ststu Status7C4F { get; set; }

		/// <summary>
		/// FK__UserFavPr__UserI__208CD6FA_BackReference (dbo.UserFavProduct)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="UserId", CanBeNull=true)]
		public IEnumerable<UserFavProduct> UserFavPrUserI208CD6Fas { get; set; }

		/// <summary>
		/// FK__UserPrDat__UserI__3C69FB99_BackReference (dbo.UserPrData)
		/// </summary>
		[Association(ThisKey="Id", OtherKey="UserId", CanBeNull=true)]
		public UserPrData UserPrDatUserI3C69FB { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="UserFavProduct")]
	public partial class UserFavProduct
	{
		[Column, NotNull] public int      UserId      { get; set; } // int
		[Column, NotNull] public int      ProductId   { get; set; } // int
		[Column, NotNull] public int      ProductType { get; set; } // int
		[Column, NotNull] public DateTime DateIns     { get; set; } // datetime2(7)

		#region Associations

		/// <summary>
		/// FK__UserFavPr__UserI__208CD6FA (dbo.User)
		/// </summary>
		[Association(ThisKey="UserId", OtherKey="Id", CanBeNull=false)]
		public User User { get; set; }

		/// <summary>
		/// FK__UserFavPr__Produ__2180FB33 (dbo.TypeProduct)
		/// </summary>
		[Association(ThisKey="ProductType", OtherKey="Id", CanBeNull=false)]
		public TypeProduct UserFavPrProdu2180FB { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="UserPrData")]
	public partial class UserPrData
	{
		[PrimaryKey, NotNull    ] public int       UserId            { get; set; } // int
		[Column,     NotNull    ] public string    Name              { get; set; } // nvarchar(60)
		[Column,     NotNull    ] public string    LastName          { get; set; } // nvarchar(60)
		[Column,        Nullable] public string    Surname           { get; set; } // nvarchar(60)
		[Column,        Nullable] public string    TelNumber         { get; set; } // nvarchar(11)
		[Column,        Nullable] public string    SeriesPasport     { get; set; } // nvarchar(4)
		[Column,        Nullable] public string    NumberPasport     { get; set; } // nvarchar(6)
		[Column,        Nullable] public DateTime? IssuedDatePasport { get; set; } // datetime2(7)
		[Column,        Nullable] public string    IssuedPasport     { get; set; } // nvarchar(300)

		#region Associations

		/// <summary>
		/// FK__UserPrDat__UserI__3C69FB99 (dbo.User)
		/// </summary>
		[Association(ThisKey="UserId", OtherKey="Id", CanBeNull=false)]
		public User User { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Approval Find(this ITable<Approval> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static ApprovalRequest Find(this ITable<ApprovalRequest> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Basket Find(this ITable<Basket> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static BusTicket Find(this ITable<BusTicket> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static City Find(this ITable<City> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static CompanyProduct Find(this ITable<CompanyProduct> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static County Find(this ITable<County> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Link Find(this ITable<Link> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static PersonDataInRequest Find(this ITable<PersonDataInRequest> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static ProductCategory Find(this ITable<ProductCategory> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static ProductComment Find(this ITable<ProductComment> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Region Find(this ITable<Region> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Request Find(this ITable<Request> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Role Find(this ITable<Role> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Status Find(this ITable<Status> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Ststu Find(this ITable<Ststu> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TypeProduct Find(this ITable<TypeProduct> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static User Find(this ITable<User> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UserPrData Find(this ITable<UserPrData> table, int UserId)
		{
			return table.FirstOrDefault(t =>
				t.UserId == UserId);
		}
	}
}

